apiVersion: apps/v1
kind: Deployment
metadata:
 name: automation
 labels:
  app: automation
spec:
 replicas: 1
 selector:
  matchLabels:
   app: automation
 template:
  metadata:
   labels:
    app: automation
  spec:
   serviceAccountName: automation
   containers:
    - name: automation
      image: dsdeuwacr.azurecr.io/aksdemo:latest
   imagePullSecrets:
   - name: regcred